name: oil-change-point-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - jupyterlab
  - flask
  - pymc3
  - arviz
  - pip:
      - flask-cors
      - python-dotenv
      - streamlit
